import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useNavigate } from 'react-router-dom';
import { Container } from '../components/ui/Container';
import { useAuth } from '../context/useAuth';
import './Auth.css';

export function Signup() {
  const navigate = useNavigate();
  const { signup } = useAuth();
  const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '' });
  const [errors, setErrors] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const submit = (event) => { event.preventDefault(); const next = {}; if (!form.name.trim()) next.name = 'Name is required.'; if (!form.email.trim()) next.email = 'Email is required.'; else if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (form.password.length < 8) next.password = 'Password must be at least 8 characters.'; if (form.password !== form.confirmPassword) next.confirmPassword = 'Passwords must match.'; setErrors(next); if (!Object.keys(next).length) { signup(form); setSubmitted(true); window.setTimeout(() => navigate('/'), 700); } };
  const update = (event) => { setForm({ ...form, [event.target.name]: event.target.value }); setErrors({ ...errors, [event.target.name]: undefined }); };
  return <main className="fv-auth-page"><Container><section className="fv-auth-panel" aria-labelledby="signup-heading"><div className="fv-auth-kicker">ACCOUNT / DEMO AUTHENTICATION</div><h1 id="signup-heading">Create an account</h1><p className="fv-auth-intro">This creates a temporary frontend demonstration only. A demo credential fingerprint is kept in this browser for the login walkthrough; no server account is created.</p>{submitted ? <div className="fv-form-success" role="status"><strong>Demo account created successfully.</strong><p>Your demo profile and credential fingerprint were saved locally for this browser. No server account was created.</p><Link to="/login">Continue to demo login</Link></div> : <form className="fv-form" onSubmit={submit} noValidate><div className="fv-form-field"><label htmlFor="signup-name">Name</label><input id="signup-name" name="name" autoComplete="name" value={form.name} onChange={update} aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? 'signup-name-error' : undefined} />{errors.name && <span className="fv-form-error" id="signup-name-error">{errors.name}</span>}</div><div className="fv-form-field"><label htmlFor="signup-email">Email</label><input id="signup-email" name="email" type="email" autoComplete="email" value={form.email} onChange={update} aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? 'signup-email-error' : undefined} />{errors.email && <span className="fv-form-error" id="signup-email-error">{errors.email}</span>}</div><div className="fv-form-field"><label htmlFor="signup-password">Password</label><input id="signup-password" name="password" type="password" autoComplete="new-password" value={form.password} onChange={update} aria-invalid={Boolean(errors.password)} aria-describedby={errors.password ? 'signup-password-error' : undefined} />{errors.password && <span className="fv-form-error" id="signup-password-error">{errors.password}</span>}</div><div className="fv-form-field"><label htmlFor="signup-confirm-password">Confirm password</label><input id="signup-confirm-password" name="confirmPassword" type="password" autoComplete="new-password" value={form.confirmPassword} onChange={update} aria-invalid={Boolean(errors.confirmPassword)} aria-describedby={errors.confirmPassword ? 'signup-confirm-password-error' : undefined} />{errors.confirmPassword && <span className="fv-form-error" id="signup-confirm-password-error">{errors.confirmPassword}</span>}</div><button className="fv-form-submit" type="submit">Create demo account</button></form>}<p className="fv-auth-switch">Already have a demo account? <Link to="/login">Sign in</Link></p><Link className="fv-auth-back" to="/">Back to FandomVerse</Link></section></Container></main>;
}
